### ISSUE TITLE
[Feature Request] Do not disturb mode

### ISSUE THREAD

**Issue by ShagoY** [natekspencer/hacs-litterrobot#10]
Hi,

Following our discussion about the "do not disturb" mode on another post, I created this one.

After testing, here's what I discovered:
- Sleep" mode: Our LR does not detect any use/status change during this mode. So it doesn't allow to perform a cleanup at the output or to use the "Cat Sensor Timing" status.
Is this because of the API?
- "Do not disturb" mode: I tried to use a boolean input to toggle the LR on/off.
The problem is that our device automatically performs a cleaning when it is switched on whether or not it was used during this mode.

So, I imagine two new ways... 
- The use of a "pause" mode which will be triggered by the status "Cat Sensor Timing".
- Or use the "clean cycle wait time".
These are two solutions that are not yet available.

Do you see other solutions?

**Comment by natekspencer** [comment]
You are correct in that turning on the litter box when it was previously off will result in an automatic clean cycle being performed. What I was suggesting on the other thread though, was to only turn off the litter box if you are in "do not disturb" mode and a cat uses the litter box. Something like this:

Create an input boolean for "do not disturb"

Create the following automations:

- Automation A (enable do not disturb):
  - trigger: start netflix, baby sleeping, dj party, etc
  - action: set "do not disturb" input boolean to true

- Automation B (cat used litter box while "do not disturb"):
  - trigger: litter box status code changes to "CST"
  - condition: "do not disturb" input boolean is true
  - action: turn off litter box

- Automation C (disable do not disturb):
  - trigger: turn off netflix, baby is awake, party is over, etc
  - action:
    - set "do not disturb" input boolean to false
    - turn on litter box

To explain:
- Automation A should only set the input boolean to true, it should not turn off your litter box.
- Automation B should only turn off the litter box if it sees your cat use the litter box (status code "CST") and the input boolean is true.
- Automation C sets the input boolean to false and also turns on the litter box. If Automation B was never triggered, then turning on the litter box from an already on state should have no effect, since it is already on. As such, a clean cycle won't be performed. Optionally, you could split this automation into two separate automations as follows:
  - Automation C (disable do not disturb):
    - trigger: turn off netflix, baby is awake, party is over, etc
    - action: set "do not disturb" input boolean to false
  - Automation D (turn on litter box after do not disturb, if it is off):
    - trigger: "do not disturb" changes to false
    - condition: litter box is off
    - action: turn on litter box

**Comment by natekspencer** [comment]
> * Or use the "clean cycle wait time".

Clean cycle wait time only supports 3, 7, and 15 minute intervals. So you would get at most 15 minutes of "do not disturb" if you attempted this route.

**Comment by ShagoY** [comment]
Thanks Natekspencer for your automation idea.
It does indeed work, I think I'll try to do it with sleep mode instead of turning off the LR. The concept remains the same :)

Thanks again.
