### ISSUE TITLE
Error with HA integration

### ISSUE THREAD

**Issue by ShagoY** [natekspencer/hacs-litterrobot#9]
Hello natekspencer :)

I've just tested your [HA integration](https://github.com/home-assistant/core/tree/dev/homeassistant/components/litterrobot) and I encounter a little problem with the command set_sleep_mode.

I use two automations that put my LT in "sleep" mode when I watch Netflix and others.
It worked fine with the HACS version even if I had to use utcnow() instead of now() to return the time correctly.
Also i don't really understand why because my HA installation returns my time zone correctly.

Here are the errors that HA returns to me:
```
service: vacuum.send_command
data:
  command: set_sleep_mode
  params:
    enabled: true
    sleep_time: '{{ utcnow().strftime("%H:%M:%S") }}'
target:
  entity_id: vacuum.lilas_litter_box
```
```
ERROR (MainThread) [homeassistant] Error doing job: Exception in callback async_track_point_in_utc_time.<locals>.run_action() at /usr/src/homeassistant/homeassistant/helpers/event.py:1181
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1200, in run_action
    hass.async_run_hass_job(job, utc_point_in_time)
  File "/usr/src/homeassistant/homeassistant/core.py", line 438, in async_run_hass_job
    return self.async_add_hass_job(hassjob, *args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 370, in async_add_hass_job
    task = self.loop.create_task(hassjob.target(*args))
TypeError: async_request_refresh() takes 1 positional argument but 2 were given
```

```
service: vacuum.send_command
data:
  params:
    enabled: false
  command: set_sleep_mode
target:
  entity_id: vacuum.lilas_litter_box
```
```
ERROR (MainThread) [homeassistant] Error doing job: Exception in callback async_track_point_in_utc_time.<locals>.run_action() at /usr/src/homeassistant/homeassistant/helpers/event.py:1181
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1200, in run_action
    hass.async_run_hass_job(job, utc_point_in_time)
  File "/usr/src/homeassistant/homeassistant/core.py", line 438, in async_run_hass_job
    return self.async_add_hass_job(hassjob, *args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 370, in async_add_hass_job
    task = self.loop.create_task(hassjob.target(*args))
TypeError: async_request_refresh() takes 1 positional argument but 2 were given
```

So I would like to have your opinion on this type of use... I wonder if using the sleep mode is the right way to go because the way Litter-Robot works is not to launch a cleanup at the end of the sleep mode.

You, who did the reverse engineering of the API, do you think you have a better solution to prevent our LT from launching a cleaning during a period of time and that at the end of it, the cleaning is launched if it has been used in the meantime ?

**Comment by natekspencer** [comment]
Can you report this issue on the official HA repository since it is related to that code base now? (https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml&title=)

I have a pull request that addresses the issue already and adds a couple of other sensors. But if there is a bug report on it, then it might be expedited as far as releases go.

To address your other questions:

While I don't use the sleep mode as you are attempting to do, it's a fun scenario to think about. Sort of a "do not disturb mode". I just have mine set to sleep for the night so it doesn't interrupt my own sleep. Thus, I don't really enable/disable it frequently. My LR usually performs a clean cycle after sleep mode has ended. I assume that it is because my cats have used it at some point during the night and that the unit is aware that it should cycle when sleep mode ends because of this.

That being said, I'm not sure if turning off sleep mode then removes that data point, resulting in the LR "forgetting" that a cat was inside and just starts over as being "Ready". I only have access to what is reported via their API, and not all the other internal workings of the unit itself.

Have you validated that your cats have actually used the LR while sleep mode is activated during one of your "do not disturb" modes? And that subsequently a clean cycle is not performed when sleep mode is disabled?

If so, you may want to address the issue a little differently. You might want to create an "input_boolean" for this "do not disturb" mode. Then, while true, if the unit reports "Cat Sensor Timing", you could turn off the unit. And then when you exit that mode, you could turn on the unit. That way, a clean cycle happens when you turn it on if it was previously off.

**Comment by natekspencer** [comment]
Just another clarification around the error you are receiving:

The unit actually is entering/exiting sleep mode appropriately. The error is just preventing the component from triggering a refresh to update the value a few seconds later.

**Comment by ShagoY** [comment]
Hi,

My Issue is here : [https://github.com/home-assistant/core/issues/47514](https://github.com/home-assistant/core/issues/47514)

Otherwise I can confirm that our LT "forgets" that it has been used in sleep mode.
This seems to be the way the Litter-robot engineers wanted it to work unfortunately.
That's why I asked you for your opinion :)

On the other hand, I'm not sure that our LT will raise the "Cat Sensor Timing" status when it is in Sleep mode... I'll test it to be sure.
If this is the case, using an input_boolean could be a solution !
Also, there is no "pause" mode on our LT?.
